
temperature_thresholds: # in seconds
    lower_limit: !!int 20
    upper_limit: !!int 30
    alert_limit: !!int 40
    corridor_size: !!int 5

test_values: # TODO remove after testing
    upper: !!int 70
    lower: !!int 20

status_messages:
    normal: !!str "asdf"

execution_specs:
    update_interval: !!int 60 # in seconds
    csv_folder_path: !!str "logs/"

csv_headers:
    timestamp: !!str "Time"
    reading: !!str "Reading"

stats:
    sample_size: !!int 5

# TODO attributes to make modifiable:
    # temp_thresholds
    # update_interval