
temperature_thresholds: # in seconds
    lower_limit: 20
    upper_limit: 30
    alert_limit: 40
    corridor_size: 5

test_values: # TODO remove after testing
    upper: 70
    lower: 20

status_messages:
    normal: "asdf"

execution_specs:
    update_interval: 60 # in seconds
    csv_folder_path: "logs/"

