analysis_specs:
  interval_minutes: 5
execution_specs:
  update_interval: 60
sqlite:
  column_names:
    max: Max
    mean: Mean
    median: Median
    reading: Reading
    timestamp: Timestamp
  db_name: test2.db
  table_name: temp_readings
status_messages:
  normal: asdf
temperature_thresholds:
  alert_limit: 40
  corridor_size: 5
  hysteresis_threshold: 5
  lower_limit: 20
  upper_limit: 80
  warning_limit: 35
test_values:
  lower: 20
  upper: 70
