analysis_specs:
  interval_minutes: 5
authorization:
  admins: -admin
db:
  column_names:
    dew_point: Dew_Point
    hour_interval: Hour_Interval
    humidity: Humidty
    max: Max
    mean: Mean
    median: Median
    pressure: Pressure
    pump_activation: Pump_Activation
    temperature: Temperature
    timestamp: Timestamp
    update_interval: Update_Interval
    weekday: Weekday
  db_name: test5.db
  retention_days: 30
  round_decimal: 1
  table_name: Readings
execution_specs:
  update_frequency: 30
temperature_thresholds:
  activation_threshold: 40
  alert_limit: 40
  deactivation_threshold: 30
  warning_limit: 35
test_values:
  lower: 20
  upper: 70
